Vagrant.configure(2) do |config|
  config.vm.define "webserver" do |webserver|
    webserver.vm.box = "ubuntu/trusty64"
    webserver.vm.network "private_network", ip: "192.168.1.253"
    webserver.vm.hostname = "webserver"
  end
config.vm.define "ansible" do |ansible|
  ansible.vm.box = "ubuntu/trusty64"
  ansible.vm.network "private_network", ip: "192.168.1.254"
  ansible.vm.hostname = "ansible"
  ansible.vm.provision "shell", inline: <<-SHELL
    sudo apt-get update
     sudo apt-get install -y ansible
   SHELL
  end
end
